config/routes.rb
Rails.application.routes.draw do
  root   'products#index'

  get    'password_resets/new'
  get    'password_resets/edit'

  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  get    '/signup',                   to: 'users#new'

  get    '/dashboard',                to: 'dashboard#index'

  resources :users
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new create edit update]
  
  resource :cart,                 only: %i[show destroy]

  resources :orders, only: %i[create index] do 
    patch :toggle_handled, on: :member
  end
  
  resources :products do 
    post :add_to_cart,      on: :member
    post :remove_from_cart, on: :member
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :product_carts, dependent: :destroy
  has_many :products, through: :product_carts, foreign_key: :cart_id

  def add_product!(product_id)
    if product_ids.include?(product_id)
      product_carts.find_by(product_id: product_id).increment!(:quantity)
    else 
      products << Product.find(product_id)
    end
  end

  def remove_product!(product_id)
    return unless product_ids.include?(product_id)

    product_cart = product_carts.find_by(product_id: product_id)
    
    if product_cart.quantity == 1
      product_cart.delete
    else
      product_cart.decrement!(:quantity)
    end
  end

  def count
    product_carts.sum(:quantity)
  end

  def total_price
    product_carts.inject(0) { |sum, product_cart| sum += product_cart.quantity * products.find(product_cart.product_id).price }
  end
end

app/controllers/carts_controller.rb
class CartsController < BaseController
  before_action :check_logged_in_user
  before_action :retrieve_user_cart

  def show; end

  def destroy 
    @cart.destroy

    redirect_to(root_url)
  end
end

app/views/carts/show.html.haml
%h1.page-title Shopping Cart

- if @cart && @cart.products.any?
  .row
    .col-md-5.col-md-offset-3
      %ul.list-group
        - @cart.products.each do |product|
          %li.list-group-item.list-group-item-action.d-flex.justify-content-between.align-items-center
            .flex-custom
              .flex-column
                %strong
                  = product.title
                %br 
                = "Price: $#{product.price}" 
                %br 
                = link_to '+', add_to_cart_product_path(product), method: :post, class: 'label label-pill label-primary'
                = "Quantity: #{@cart.product_carts.find_by(product: product).quantity}"
                = link_to '-', remove_from_cart_product_path(product), method: :post, class: 'label label-pill label-primary'
              .image-parent 
                = image_tag product.image, class: 'img-fluid', alt: product.title
                
      = "Total price: $#{@cart.total_price}"
      %br
      = link_to 'Empty cart', cart_path, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }
      = link_to 'Place order', orders_path, method: :post, class: 'btn btn-primary'
- else 
  %h3= 'Cart is empty.'