config/routes.rb
Rails.application.routes.draw do
  root   'products#index'

  get    'password_resets/new'
  get    'password_resets/edit'

  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  get    '/signup',                   to: 'users#new'

  get    '/dashboard',                to: 'dashboard#index'

  resources :users
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new create edit update]
  
  resource :cart,                 only: %i[show destroy]

  resources :orders, only: %i[create index] do 
    patch :toggle_handled, on: :member
  end
  
  resources :products do 
    post :add_to_cart,      on: :member
    post :remove_from_cart, on: :member
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_carts, dependent: :destroy
  has_many :carts, through: :product_carts, foreign_key: :product_id

  has_many :product_orders, dependent: :destroy 
  has_many :orders, through: :product_orders, foreign_key: :product_id

  has_one_attached :image
  validates :title, length: { maximum: 25 }, presence: true
  validates :description, length: { maximum: 50 }, presence: true
  validates :price, presence: true, numericality: { only_float: true, greater_than: 0 }
end

app/controllers/products_controller.rb
class ProductsController < BaseController
  before_action :check_logged_in_user
  before_action :set_product,        only: %i[show edit update destroy]
  before_action :retrieve_user_cart, only: %i[add_to_cart remove_from_cart]

  def index
    @products = Product.all
  end

  def show; end

  def edit; end
  
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.image.attach(product_params[:image])

    if @product.save
      flash[:success] = 'Product added successfully!'

      redirect_to(@product) 
    else 
      render 'new'
    end
  end

  def update
    if @product.update(product_params)
      flash[:success] = 'Product updated successfully!'

      redirect_to(@product) 
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = 'Product deleted!'

    redirect_to(dashboard_path)
  end

  def add_to_cart
    @cart = Cart.create(user: current_user) if @cart.nil?
    @cart.add_product!(params[:id].to_i)

    redirect_back(fallback_location: root_url)
  end

  def remove_from_cart
    @cart.remove_product!(params[:id].to_i)

    redirect_back(fallback_location: root_url)
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :image)
    end
end

app/views/products/_form.html.haml
= form_with(model: product) do |form|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.each do |error|
          %li= error.full_message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.text_field :description
  .field 
    = form.label :price
    = form.text_field :price
  .field 
    = form.label :image
    = form.file_field :image, direct_upload: true
  .actions
    = form.submit

app/views/products/edit.html.haml
%h1 Editing Product

= render 'form', product: @product

= link_to 'Show', @product
= link_to 'Back', dashboard_path

app/views/products/index.html.haml
%main
  .grid-container
    #container.custom-container
      - @products.each do | product |
        .dish
          =image_tag(product.image, class: 'food-image')
          .info 
            %p.dish-name= product.title 
            %p.description= product.description 
            %p.price= "$#{product.price}"
            = link_to 'Add to cart', add_to_cart_product_path(product), method: :post

app/views/products/new.html.haml
%h1 New product 
= render('form', product: @product)

= link_to 'Back', dashboard_path

app/views/products/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @product.title
%p
  %strong Description:
  = @product.description
%p
  %strong Price: 
  = @product.price 
%p
  %strong Image: 
  = image_tag @product.image, class: 'img-fluid'

= link_to 'Edit ', edit_product_path(@product)
= link_to 'Delete ', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'Back ', dashboard_path