config/routes.rb
Rails.application.routes.draw do
  root   'products#index'

  get    'password_resets/new'
  get    'password_resets/edit'

  get    '/login',                    to: 'sessions#new'
  post   '/login',                    to: 'sessions#create'
  delete '/logout',                   to: 'sessions#destroy'
  get    '/signup',                   to: 'users#new'

  get    '/dashboard',                to: 'dashboard#index'

  resources :users
  resources :account_activations, only: :edit
  resources :password_resets,     only: %i[new create edit update]
  
  resource :cart,                 only: %i[show destroy]

  resources :orders, only: %i[create index] do 
    patch :toggle_handled, on: :member
  end
  
  resources :products do 
    post :add_to_cart,      on: :member
    post :remove_from_cart, on: :member
  end
end

app/views/layouts/_header.html.haml
%header.header-wrapper
  %img.logo{src: '/logo.png'}
  %p.logo-text
    Eureka
    %br
    Caffe 
  %nav.navigation
    %ul.nav-list
      %li= link_to 'HOME', root_path 
      %li= link_to 'ABOUT', '#' 
      %li= link_to 'SERVICE', '#' 
      - if logged_in?
        %li
          = link_to 'CART', cart_path
          %label.badge.badge-pill= cart_count
        - if current_user.admin?
          %li= link_to 'ORDERS', orders_path
        %li= link_to 'LOG OUT', logout_path, method: :delete 
      - else 
        %li= link_to 'LOG IN', login_path
  %h1#title.text Ordering food 
  %p.text You can order food in many ways. There are many algorithms out there that you can use to order food.
  %p.text The only optimal ones, however, are quicksort and heapsort.

app/views/layouts/_options_bar.html.haml
.options-bar
  #category-option.dropdown
    %p.drop-text 
      CATEGORY
      %span.custom-caret ⌄
    .dropdown-content 
      %p PASTA 
      %p PIZZA 
      %p SOUP 
      %p SALAD 

  #sorting-option.dropdown
    %p.drop-text
      SORTING
      %span.custom-caret ⌄
    .dropdown-content 
      %p A-Z
      %p Z-A
      %p Price: L-H 
      %p Price: H-L

  #vegetarian-option.dropdown
    %p.drop-text
      VEGETARIAN
      %span.custom-caret ⌄
    .dropdown-content 
      %p VEGETARIAN
      %p VEGAN
      %p NON-VEGETARIAN
  
  %p#price-option PRICE 
  %p#min-price-option.price-option $15
  %input#price-range-bar{type: 'range', name: 'price', min: '15', max: '100'}
  %p#max-price-option.price-option $100

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Eureka Caffe
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render('layouts/header')
    = render('layouts/options_bar')
    .container 
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = debug(params) if Rails.env.development?